language: go

sudo: required

env:
  - GO111MODULE=on

services:
  - docker

go:
  - "1.12.x"


stages:
  - test
  - build
  - deploy

jobs:
  include:
    - stage: test
      script: make unit-test
    - stage: build
      script: docker
    - stage: deploy
      if: branch = master
      script:
        - make create-kube-config
        - make install-kubectl
        - ENVIRONMENT=production NAMESPACE=default envsubst <  k8s_scrapper.yml | kubectl apply -f -
