apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ${ENVIRONMENT}-fortune-scrapper
  namespace: ${NAMESPACE}
  labels:
    application: ${ENVIRONMENT}-fortune-scrapper
    environment: ${ENVIRONMENT}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      application: ${ENVIRONMENT}-fortune-scrapper
      environment: ${ENVIRONMENT}
  template:
    metadata:
      labels:
        application: ${ENVIRONMENT}-fortune-scrapper
        environment: ${ENVIRONMENT}
    spec:
      containers:
        - name: ${ENVIRONMENT}-fortune-scrapper
          image: "thiagotr/fortune-scrapper"
          imagePullPolicy: Always
          env:
            - name: ENABLE_CRON
              value: "true"
            - name: CRON_INTERVAL
              value: 10s
            - name: FORTUNE_APP_SAVE_ENDPOINT
              value: https://app.fortune.opsadventures.com/v1/fortune
            - name: MESSAGE_SOURCE_ENDPOINT
              value: http://dojodevopschallenge.s3-website-eu-west-1.amazonaws.com/fortune_of_the_day.json
            